/**
 * This module contains functions related to cairo's XLib
 * functionality.
 *
 * This file is automatically generated; do not directly modify.
 *
 * Authors: Daniel Keep
 * Copyright: 2006, Daniel Keep
 * License: BSD v2 (http://www.opensource.org/licenses/bsd-license.php).
 */
/*
 * Copyright © 2006 Daniel Keep
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 * * Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * * Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in the
 *   documentation and/or other materials provided with the distribution.
 *
 * * Neither the name of this software, nor the names of its contributors
 *   may be used to endorse or promote products derived from this software
 *   without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
 * TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
module cairo.xlib.cairofuncs_xlib;

private
{
    import cairo.loader;
    import cairo.xlib.cairotypes_xlib;
}

package void cairo_xlib_loadprocs(SharedLib lib)
{
    // cairo functions
    cairo_xlib_surface_create = cast(pf_cairo_xlib_surface_create)getProc(lib, "cairo_xlib_surface_create");
    cairo_xlib_surface_create_for_bitmap = cast(pf_cairo_xlib_surface_create_for_bitmap)getProc(lib, "cairo_xlib_surface_create_for_bitmap");
    cairo_xlib_surface_set_size = cast(pf_cairo_xlib_surface_set_size)getProc(lib, "cairo_xlib_surface_set_size");
    cairo_xlib_surface_set_drawable = cast(pf_cairo_xlib_surface_set_drawable)getProc(lib, "cairo_xlib_surface_set_drawable");
}

extern(C):

typedef cairo_surface_t* function(Display* dpy, Drawable drawable, Visual* visual, int width, int height) pf_cairo_xlib_surface_create;
typedef cairo_surface_t* function(Display* dpy, Pixmap bitmap, Screen* screen, int width, int height) pf_cairo_xlib_surface_create_for_bitmap;
typedef void function(cairo_surface_t* surface, int width, int height) pf_cairo_xlib_surface_set_size;
typedef void function(cairo_surface_t* surface, Drawable drawable, int width, int height) pf_cairo_xlib_surface_set_drawable;

pf_cairo_xlib_surface_create cairo_xlib_surface_create;
pf_cairo_xlib_surface_create_for_bitmap cairo_xlib_surface_create_for_bitmap;
pf_cairo_xlib_surface_set_size cairo_xlib_surface_set_size;
pf_cairo_xlib_surface_set_drawable cairo_xlib_surface_set_drawable;

